"""add subject to exams table

Revision ID: 3734621c2577
Revises: 
Create Date: 2026-07-06 15:28:58.813891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3734621c2577'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exams', sa.Column('subject', sa.String(length=20), nullable=False, server_default='通用'))
    op.create_index(op.f('ix_exams_subject'), 'exams', ['subject'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exams_subject'), table_name='exams')
    op.drop_column('exams', 'subject')
    # ### end Alembic commands ###
